### PR TITLE
Fix linked objctive-C symbols on old macOS versions

### LINKED ISSUE #45: Possible version mismatch in CoreFoundation.framework
See https://github.com/tauri-apps/tauri/issues/4387

I built a tauri app which includes mac-notification-sys, and one that doesn't. Both were built from macOS 12.4 with XCode 13 and 14 beta (no difference). It appears that our usage of this lib caused a "missing symbol" dyld linking error when loading the app on macOS 10.13-10.13.6 (at minimum, might affect more versions), but I don't know if it's a bug in tauri or in the build step here. So consider this issue informational for now.

The reason I'm posting here at all is because Tauri has a lot of Obj C dependencies, but this is the only one that appears to trigger a linking failure like this. 

Anyway, if anyone has experience deploying to multiple versions of macOS, this could be extremely helpful. I suspect there's a version mismatch with dynamic linking to libraries, but this is over my head. Nevertheless I really hope we can fix this.

### PR DESCRIPTION
**Pull request by BlackHoleFox**
Closes #45

With these changes, the symbol table for binaries using this crate looks more correct for older macOS builds. By default on a M1:
```
~/x/leak_hunting [master +4 ~0 -0 !] ▶ nm ./target/debug/leak_hunting | rg _OBJC_CLASS_
                 U _OBJC_CLASS_$_NSAppleScript
                 U _OBJC_CLASS_$_NSBundle
                 U _OBJC_CLASS_$_NSConstantDictionary
                 U _OBJC_CLASS_$_NSConstantIntegerNumber
                 U _OBJC_CLASS_$_NSDate
                 U _OBJC_CLASS_$_NSDictionary
                 U _OBJC_CLASS_$_NSImage
                 U _OBJC_CLASS_$_NSObject
                 U _OBJC_CLASS_$_NSRunLoop
                 U _OBJC_CLASS_$_NSString
                 U _OBJC_CLASS_$_NSThread
                 U _OBJC_CLASS_$_NSURL
                 U _OBJC_CLASS_$_NSUserNotification
                 U _OBJC_CLASS_$_NSUserNotificationCenter
0000000100068748 S _OBJC_CLASS_$_NotificationCenterDelegate
0000000100068398 s __OBJC_CLASS_PROTOCOLS_$_NotificationCenterDelegate
00000001000684a8 s __OBJC_CLASS_RO_$_NotificationCenterDelegate
```

With `MACOSX_DEPLOYMENT_TARGET="10.14"` set:
```
~/x/leak_hunting [master +4 ~0 -0 !] ▶ nm ./target/debug/leak_hunting | rg _OBJC_CLASS_
                 U _OBJC_CLASS_$_NSAppleScript
                 U _OBJC_CLASS_$_NSBundle
                 U _OBJC_CLASS_$_NSDate
                 U _OBJC_CLASS_$_NSDictionary
                 U _OBJC_CLASS_$_NSImage
                 U _OBJC_CLASS_$_NSNumber
                 U _OBJC_CLASS_$_NSObject
                 U _OBJC_CLASS_$_NSRunLoop
                 U _OBJC_CLASS_$_NSString
                 U _OBJC_CLASS_$_NSThread
                 U _OBJC_CLASS_$_NSURL
                 U _OBJC_CLASS_$_NSUserNotification
                 U _OBJC_CLASS_$_NSUserNotificationCenter
0000000100068a38 S _OBJC_CLASS_$_NotificationCenterDelegate
0000000100068668 s __OBJC_CLASS_PROTOCOLS_$_NotificationCenterDelegate
0000000100068778 s __OBJC_CLASS_RO_$_NotificationCenterDelegate
```

Additionally, and probably importantly, the dictionary symbols better match what XCode produces with the relevant target versions. @betamos can you try this with Tauri on 10.14/10.13?

### CODE REVIEW

**Comment by betamos** [comment]
Confirming! I built a universal binary with Tauri using `minimumSystemVersion: 10.13` in my tauri.conf.json.

Tauri build (tauri-cli 1.0.4) apparently **does not** set the `MACOSX_DEPLOYMENT_TARGET` env var flag (it does set it for rustc, but it doesn't propagate to the build.rs in mac-notification-sys). I consider this a bug on the Tauri side and will file an issue there - don't worry about that atm.

Anyway, due to the way you set the default to 10.8, it worked anyway. 🎉

More hairy details about what happened:

- I'm building a universal binary which combines aarch64 and x86_64 binaries under the hood in tauri build.
- The NSConstantDictionary was present in the aarch64 but not in the x86_64 build (again, expected due to your defaults).
- As such, the symbol was present in the combined universal build.
- ...But this was not a problem, due to the way universal binaries work. The resulting app/.dmg did launch without the dyld error.

LGTM!

File: build.rs [hunk 1]
```diff
@@ -1,11 +1,29 @@
...
+
+const DEPLOYMENT_TARGET_VAR: &str = "MACOSX_DEPLOYMENT_TARGET";
 
 fn main() {
     if cfg!(target_os = "macos") {
+        let min_version = match env::var(DEPLOYMENT_TARGET_VAR) {
+            Ok(ver) => ver,
+            Err(_) => String::from(match env::var("CARGO_CFG_TARGET_ARCH").unwrap().as_str() {
+                "x86_64" => "10.8", // NSUserNotificationCenter first showed up here.
+                "aarch64" => "11.0", // Apple silicon started here.
```
Comment (betamos) [inline build.rs:12]: Optional: Unless you know something I don't, I would skip the aarch64 default and just go with 10.8 for both. I imagine Apple has already thought about this and have mitigations in place. Why? One less input variable to worry about, to simplify future hairy debugging issues like this one.

Comment (BlackHoleFox) [reply build.rs:12]: I can add a link to it, but this is also what rustc's Apple base target definition uses (I would have copy pasted the x86 one too but 10.7 is too old). M1/M2 chips can't run on anything older than 11.

Comment (betamos) [reply build.rs:12]: Ah, thanks for the context. Doing the same as rustc seems better. Thanks.

**Comment by betamos** [comment]
Just a friendly reminder: please consider getting this in and pushing a new minor release. Mac compatibility is broken atm :(

Thank you!

**Comment by lucasfernog** [comment]
I would love to see this patch getting merged too!

**Comment by hoodie** [comment]
thank you!

**Comment by hoodie** [comment]
habemus `v0.5.6`
